/**
 * PPCH Medical Equipment Tracking & Evaluation System
 * Configuration & Master Seed Data
 */

window.PPCH_CONFIG = {
  appName: 'PPCH Medical Equipment Custody & Evaluation Suite',
  hospitalName: 'โรงพยาบาลพิษณุเวช (Phitsanuvej Hospital)',
  storageKey: 'ppch_med_track_v1',
  adminPin: 'ppch1234',
  defaultGasUrl: 'https://script.google.com/macros/s/AKfycbz8oIgnJWUcji2DaPI8CSBrPd22BFjL9A9Ui9mhamLCkRV7FVYGNWBKYJvZbjq31KE36g/exec',
  todayDate: '2026-09-30', // Contextual date
  
  // Standardized PPCH Departments
  departments: [
    { id: 'CENTRAL', name: 'คลังเครื่องมือแพทย์ส่วนกลาง (Central Supply)' },
    { id: 'ER', name: 'แผนกอุบัติเหตุและฉุกเฉิน (ER)' },
    { id: 'ICU', name: 'แผนกผู้ป่วยหนัก (ICU)' },
    { id: 'OR', name: 'แผนกห้องผ่าตัด (OR)' },
    { id: 'WARD23', name: 'แผนกหอผู้ป่วยใน ชั้น 2-3 (Ward 2-3)' },
    { id: 'WARD45', name: 'แผนกหอผู้ป่วยใน ชั้น 4-5 (Ward 4-5)' },
    { id: 'LR', name: 'แผนกห้องคลอดและทารกแรกเกิด (LR)' },
    { id: 'OPD', name: 'แผนกผู้ป่วยนอก (OPD)' },
    { id: 'OPD2', name: 'แผนกผู้ป่วยนอก 2 (OPD 2)' },
    { id: 'XRAY', name: 'แผนกรังสีวิทยา (X-Ray)' },
    { id: 'REHAB', name: 'แผนกกายภาพบำบัด' },
    { id: 'HEMODIALYSIS', name: 'ศูนย์ไตเทียม (Hemodialysis)' },
    { id: 'CATHLAB', name: 'ห้องปฏิบัติการสวนหัวใจ (Cath Lab)' },
    { id: 'FACILITY', name: 'แผนกวิศวกรรมชีวการแพทย์และอาคาร' },
    { id: 'LAB', name: 'แผนกห้องปฏิบัติการทางการแพทย์ (Laboratory)' }
  ],

  // 8 Evaluation Forms (ตรงตาม Google Form เดิมทั้ง 8 ชุด)
  forms: [
    {
      id: 'defibrillator',
      name: 'แบบตรวจเช็ค Defibrillator (เครื่องกระตุกหัวใจ)',
      shortName: 'Defibrillator',
      category: 'เครื่องมือกู้ชีพวิกฤต',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'zap',
      badgeColor: 'red',
      description: 'ตรวจเช็คความพร้อมระบบช็อกไฟฟ้า แบตเตอรี่สำรอง แผ่น Paddle และกระดาษพิมพ์ผล',
      items: [
        'สภาพสายไฟ ปลั๊กไฟ และสายต่อเชื่อม ไม่ชำรุด ฉีกขาด หรือหักงอ',
        'ระดับแบตเตอรี่สำรอง (Battery Status) เต็มหรือพร้อมใช้งานเมื่อเกิดไฟฟ้าดับ',
        'แผ่น Paddles / อุปกรณ์นำไฟฟ้า (Electrode Pads) ครบ สะอาด และไม่หมดอายุ',
        'ผลการทำ Routine Self-Test (ผ่านเกณฑ์ 100% ไม่มี Error Code)',
        'ระบบทดสอบการช็อกพลังงาน (Discharge Test 30-50 Joules) สัญญาณพร้อมช็อกทำงานปกติ',
        'กระดาษบันทึกผล EKG Strip มีเพียงพอในตัวเครื่อง',
        'ความสะอาดของตัวเครื่องและอุปกรณ์ประกอบ พร้อมใช้งานทันที'
      ]
    },
    {
      id: 'ventilator',
      name: 'แบบตรวจเช็คเครื่อง Ventilator (เครื่องช่วยหายใจ)',
      shortName: 'Ventilator',
      category: 'เครื่องมือกู้ชีพวิกฤต',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'activity',
      badgeColor: 'red',
      description: 'ตรวจเช็ควงจรช่วยหายใจ ออกซิเจน ระบบ Pre-use Check และระบบเสียง Alarm',
      items: [
        'ระบบต่อท่อก๊าซออกซิเจน (O2) และท่อลม (Air) แน่นหนา ไม่มีเสียงรั่วซึม',
        'สายไฟหลักและระดับประจุแบตเตอรี่สำรองพร้อมทำงานต่อเนื่องอย่างน้อย 30-60 นาที',
        'วงจรท่อช่วยหายใจ (Breathing Circuit) สะอาด ปลอดเชื้อ และติดตั้ง Flow Sensor ถูกต้อง',
        'ผลการทดสอบ Pre-use Check / Tightness Check ผ่านทุกขั้นตอน',
        'ระบบสัญญาณเตือนภาพและเสียง (Audio & Visual Alarm) ทำงานปกติเมื่อจำลองภาวะผิดปกติ',
        'ตัวกรองฝุ่นและแผ่นดักความชื้น (Expiratory Filter) แห้ง สะอาด ไม่อุดตัน'
      ]
    },
    {
      id: 'high_flow',
      name: 'แบบตรวจเช็คเครื่อง High Flow Nasal Cannula (HHHFINC)',
      shortName: 'High Flow (HHHFINC)',
      category: 'เครื่องมือระบบทางเดินหายใจ',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'wind',
      badgeColor: 'amber',
      description: 'ตรวจเช็คหม้อต้มทำความชื้น ท่อให้ความร้อน Breathing Circuit และสายวัดอุณหภูมิ',
      items: [
        'สายไฟ ปลั๊กไฟ และระบบจ่ายไฟหลักทำงานปกติ',
        'ชุดทำความชื้น (Humidifier Chamber) และน้ำ Sterile Water สำหรับเติมอยู่ในระดับที่กำหนด',
        'สายส่งก๊าซแบบปรับอุณหภูมิ (Heated Breathing Tube) ต่อแน่นหนา ไม่ฉีกขาด',
        'ระบบควบคุมอุณหภูมิและการตั้งค่า FiO2 ตอบสนองได้ตามสเปก',
        'สัญญาณเตือนการอุดตันของท่อ (Occlusion Alarm) และน้ำหมดทำงานปกติ'
      ]
    },
    {
      id: 'infusion_pump',
      name: 'แบบตรวจเช็ค INFUSION PUMP (เครื่องให้สารน้ำ)',
      shortName: 'Infusion Pump',
      category: 'เครื่องมือควบคุมการให้ยา/สารน้ำ',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'droplet',
      badgeColor: 'blue',
      description: 'ตรวจเช็ค Drop Sensor ตัวหนีบล็อคสาย การหยด และสัญญาณเตือนการอุดตัน',
      items: [
        'สภาพโครงสร้างภายนอก ขาแขวน และตัวล็อคเสาน้ำเกลือแข็งแรง มั่นคง',
        'สายไฟ ปลั๊กไฟ และแบตเตอรี่สำรองสามารถใช้งานต่อเนื่องได้',
        'เซนเซอร์ตรวจจับฟองอากาศ (Air-in-line Sensor) และการอุดตัน (Occlusion) ตอบสนองแม่นยำ',
        'ตัวหนีบควบคุมการไหลอิสระ (Free-Flow Clamp / Safety Clamp) ทำงานสมบูรณ์',
        'หน้าจอแสดงอัตราการไหล (Flow Rate) คมชัด ตัวเลขไม่ขาดหาย'
      ]
    },
    {
      id: 'vital_signs',
      name: 'แบบตรวจเช็ค Vital Signs Monitor (เครื่องวัดสัญญาณชีพ)',
      shortName: 'Vital Signs Monitor',
      category: 'เครื่องมือเฝ้าระวังผู้ป่วย',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'heart',
      badgeColor: 'emerald',
      description: 'ตรวจเช็คโมดูล NIBP Cuff, SpO2 Probe, Temp Probe และเสียงเตือน Alarm Limit',
      items: [
        'สายไฟ AC และระบบประจุแบตเตอรี่ทำงานปกติ',
        'ปลอกวัดความดัน (NIBP Cuff) และสายลมไม่รั่ว บีบและวัดค่าได้ถูกต้อง',
        'เซนเซอร์วัดออกซิเจนในเลือด (SpO2 Probe) สายไม่หักงอ แสงสีแดงติดสว่างสม่ำเสมอ',
        'หน้าจอแสดงคลื่นและตัวเลขชัดเจน ปุ่มกดหรือระบบสัมผัสทำงานลื่นไหล',
        'ระบบตั้งค่าและส่งเสียงเตือนเมื่อค่าวิกฤต (Alarm Limit) ดังชัดเจน'
      ]
    },
    {
      id: 'anesthesia',
      name: 'แบบตรวจเช็คเครื่องให้ยาสลบ (Anesthesia Machine)',
      shortName: 'เครื่องให้ยาสลบ',
      category: 'เครื่องมือห้องผ่าตัด',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'shield',
      badgeColor: 'purple',
      description: 'ตรวจเช็คระบบแก๊สทางการแพทย์ Vaporizer ระบบ Scavenging และ Soda Lime',
      items: [
        'แรงดันท่อก๊าซ O2, N2O, Air จากระบบ Pipeline หรือถังก๊าซอยู่ในเกณฑ์มาตรฐาน',
        'Vaporizer ล็อคแน่นหนา ไม่มีรอยรั่วซึมของยาระเหย และปริมาณยาเพียงพอ',
        'ระบบดูดซับคาร์บอนไดออกไซด์ (Soda Lime Canister) สียังไม่เปลี่ยนสภาพ (ไม่หมดอายุ)',
        'ระบบกำจัดก๊าซดมยาส่วนเกิน (Scavenging System) ทำงานปกติ',
        'ระบบทดสอบความดันรั่วซึม (High-pressure & Low-pressure Leak Test) ผ่านเกณฑ์'
      ]
    },
    {
      id: 'ekg_monitor',
      name: 'แบบตรวจเช็คเครื่อง EKG Monitor (ตรวจคลื่นไฟฟ้าหัวใจ)',
      shortName: 'EKG Monitor',
      category: 'เครื่องมือวินิจฉัยโรคหัวใจ',
      frequency: 'daily',
      frequencyLabel: 'ประเมินทุกวัน',
      icon: 'bar-chart-2',
      badgeColor: 'teal',
      description: 'ตรวจเช็คสาย Leadwire 12 Leads กระดาษกราฟ ระบบกรองสัญญาณ และความสะอาด',
      items: [
        'สายไฟหลักและแบตเตอรี่สำรองใช้งานได้ปกติ',
        'สายสัญญาณ Leadwires ครบ 10 ขั้ว (12 Leads) ปลายสายไม่แตกหัก ไม่ขึ้นสนิม',
        'กระดาษพิมพ์ผลความร้อน (Thermal Paper) บรรจุพร้อมใช้งาน และหัวพิมพ์ชัดเจน',
        'สัญญาณ EKG บนหน้าจอไม่มีสัญญาณรบกวน (Artifact) รุนแรงเมื่อต่อกับเครื่องจำลอง',
        'ลูกยางดูดหน้าอก (Chest Electrodes) และแคลมป์หนีบแขนขา (Limb Clamps) สะอาด ไม่แตกร้าว'
      ]
    },
    {
      id: 'ultrasound',
      name: 'แบบตรวจเช็คความพร้อมใช้งาน Ultrasound (เครื่องอัลตราซาวด์)',
      shortName: 'Ultrasound',
      category: 'เครื่องมือภาพถ่ายทางการแพทย์',
      frequency: 'monthly',
      frequencyLabel: 'ประเมินเดือนละ 1 ครั้ง',
      icon: 'radio',
      badgeColor: 'indigo',
      description: 'ตรวจเช็คความสมบูรณ์ของหัวตรวจ (Probes), จอภาพ, แทร็กบอล, ล้อล็อค และการบันทึกภาพ',
      items: [
        'สายไฟ ปลั๊กไฟ และระบบตัดไฟอัตโนมัติสมบูรณ์',
        'หัวตรวจ (Probes: Convex, Linear, Cardiac) เลนส์ไม่แตก ปลอกหุ้มไม่ปริ และสายไม่พับงอ',
        'หน้าจอภาพหลักและจอสัมผัส สะอาด คมชัด ไม่มีเส้นบอด (Dead Pixels)',
        'ปุ่มปรับแต่ง Gain, Depth, Trackball และฟังก์ชันบันทึกภาพ Freeze ตอบสนองแม่นยำ',
        'ระบบเบรกล้อเข็นทั้ง 4 ล้อ ล็อคได้มั่นคง ไม่ลื่นไถล',
        'ระบบระบายความร้อน พัดลมทำงานเงียบ ไม่มีเสียงผิดปกติ และช่องกรองฝุ่นสะอาด'
      ]
    },
    // ===== แผนกห้องปฏิบัติการทางการแพทย์ (Laboratory Forms) =====
    // 1. FM-PPCH-LAB-019 แบบบันทึกปฏิบัติทดสอบเครื่องสำรองไฟห้องปฏิบัติการ UPS.xlsx
    {
      id: 'lab_ups',
      name: 'แบบบันทึกปฏิบัติทดสอบ เครื่องสำรองไฟห้องปฏิบัติการ UPS (FM-PPCH-LAB-019)',
      shortName: 'UPS Lab (สำรองไฟ)',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'quarterly',
      frequencyLabel: 'ทดสอบทุก 3 เดือน (Quarterly)',
      icon: 'zap',
      badgeColor: 'amber',
      description: 'ทดสอบโดยการดึงปลั๊กออก ทดสอบทุก 3 เดือน',
      items: [
        'ทดสอบโดยการดึงปลั๊กออก ทดสอบทุก 3 เดือน (ผลการทดสอบ: ผ่าน)'
      ]
    },
    // 2. FM-PPCH-LAB-049 Maintenance Checklist เครื่อง Cobas h232.docx
    {
      id: 'lab_cobas_h232',
      name: 'Maintenance Checklist เครื่อง Cobas h232 (FM-PPCH-LAB-049)',
      shortName: 'Cobas h232 (POC)',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน (Daily Maintenance)',
      icon: 'activity',
      badgeColor: 'blue',
      description: 'Daily Maintenance: Instrument cleaning',
      items: [
        'Instrument cleaning (ทำความสะอาดตัวเครื่อง)'
      ]
    },
    // 3. FM-PPCH-LAB-057 แบบบันทึกอุณหภูมิห้องปฏิบัติการ.docx
    {
      id: 'lab_room_temp',
      name: 'แบบบันทึกอุณหภูมิห้องปฏิบัติการ (FM-PPCH-LAB-057)',
      shortName: 'อุณหภูมิห้อง Lab',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน (วันละ 3 ครั้ง)',
      icon: 'thermometer',
      badgeColor: 'teal',
      description: 'ห้องที่จัดเก็บน้ำยา/ห้องตรวจวิเคราะห์ ควบคุมอุณหภูมิ 24-28 °C และควบคุมความชื้นไม่เกิน 60 % (วันละ 3 ครั้ง)',
      items: [
        'ควบคุมอุณหภูมิ ในช่วง 24-28 องศาเซลเซียส',
        'ควบคุมความชื้นไม่เกิน 60 %'
      ]
    },
    // 4. FM-PPCH-LAB-060 แบบบันทึกอุณหภูมิตู้แช่แข็ง.docx
    {
      id: 'lab_freezer',
      name: 'แบบบันทึกอุณหภูมิตู้แช่แข็ง (FM-PPCH-LAB-060)',
      shortName: 'ตู้แช่แข็ง (≤ -18°C)',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน (วันละ 3 ครั้ง)',
      icon: 'snowflake',
      badgeColor: 'cyan',
      description: 'ตู้แช่แข็งกำหนดให้ควบคุมอุณหภูมิไม่เกิน -18 องศาเซลเซียส (วันละ 3 ครั้ง)',
      items: [
        'ควบคุมอุณหภูมิไม่เกิน -18 องศาเซลเซียส'
      ]
    },
    // 5. FM-PPCH-LAB-061 แบบบันทึกอุณหภูมิ Waterbath.docx
    {
      id: 'lab_waterbath',
      name: 'แบบบันทึกอุณหภูมิ Waterbath (FM-PPCH-LAB-061)',
      shortName: 'Water bath (37°C)',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน (วันละ 3 ครั้ง)',
      icon: 'droplet',
      badgeColor: 'emerald',
      description: 'อุณหภูมิห้อง Waterbath กำหนดให้ควบคุมอุณหภูมิอยู่ที่ 37 องศาเซลเซียส (วันละ 3 ครั้ง)',
      items: [
        'ควบคุมอุณหภูมิอยู่ที่ 37 องศาเซลเซียส'
      ]
    },
    // 6. FM-PPCH-LAB-062 แบบบันทึกอุณหภูมิตู้เย็น.docx
    {
      id: 'lab_refrigerator',
      name: 'แบบบันทึกอุณหภูมิตู้เย็นเก็บน้ำยา (FM-PPCH-LAB-062)',
      shortName: 'ตู้เย็นเก็บน้ำยา (2-8°C)',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน (วันละ 3 ครั้ง)',
      icon: 'box',
      badgeColor: 'indigo',
      description: 'ตู้เย็นที่จัดเก็บน้ำยากำหนดให้ควบคุมอุณหภูมิ ในช่วง 2-8 องศาเซลเซียส (วันละ 3 ครั้ง)',
      items: [
        'ควบคุมอุณหภูมิ ในช่วง 2-8 องศาเซลเซียส'
      ]
    },
    // 7. FM-PPCH-LAB-091 BSC Class II (MICRO TECH).docx
    {
      id: 'lab_bsc',
      name: 'Maintenance BSC Class II (MICRO TECH) (FM-PPCH-LAB-091)',
      shortName: 'BSC Class II',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน & สัปดาห์',
      icon: 'shield',
      badgeColor: 'purple',
      description: 'Maintenance BSC Class II (MICRO TECH) โรงพยาบาลพิษณุเวช พิจิตร รายวันและรายสัปดาห์',
      items: [
        '[รายวัน ก่อนใช้งาน] Check Volume - of water column อยู่ควรที่ 0.5 ไม่เกิน 1',
        '[รายวัน หลังใช้งาน] 1. หลังใช้งานควรเปิด Brower ทิ้งไว้ 15 นาทีและเช็ดทำความสะอาดด้วย 70 % alc. ภายในตู้',
        '[รายวัน หลังใช้งาน] 2. เปิด UVC. เพื่อฆ่าเชื้อประมาณ 30 นาที + เปิด UVH เป็นเวลา 2 ชั่วโมง',
        '[รายวัน หลังใช้งาน] 3. HEPA Filter ไม่สามารถทำความสะอาดได้เอง ควรทำการสอบเทียบ (Calibration) ทุก 12 เดือน**',
        '[รายสัปดาห์] 1. ทำความสะอาดภายใน-นอกตู้ด้วย Disinfectant Towerlettes',
        '[รายสัปดาห์] 2. ทำ Smoke Test เพื่อเช็คว่าการไหลเวียนของอากาศยังทำงานได้ดี'
      ]
    },
    // 8. FM-PPCH-LAB-099 ใบรายการตรวจสอบความพร้อมใช้ และบํารุงรักษาเครื่องมือหรืออุปกรณ์ เครื่อง BS600M.pdf
    {
      id: 'lab_mindray_bs600m',
      name: 'เครื่อง Chemistry Mindray (BS600M) (FM-PPCH-LAB-099)',
      shortName: 'Chemistry Mindray',
      category: 'แผนกห้องปฏิบัติการ (Lab)',
      frequency: 'daily',
      frequencyLabel: 'ประจำวัน & สัปดาห์ (D/W)',
      icon: 'cpu',
      badgeColor: 'rose',
      description: 'ใบรายการตรวจสอบความพร้อมใช้ และบำรุงรักษาเครื่องมือหรืออุปกรณ์ เครื่อง BS600M',
      items: [
        '[Daily (1)] Check Conc. Wash Solution (เกณฑ์: มีเพียงพอต่อการใช้งาน)',
        '[Daily (2)] Clean Electrode Tubes (Automatic by analyzer *ทำในกรณีมี Electrolyte*)',
        '[Daily (3)] Special wash probe/Mixer (Automatic by analyzer)',
        '[Weekly (1)] Clean sample probe/reagent probe/Mixer Exterior (Automatic by analyzer)',
        '[Weekly (2)] Weekly Special Wash & Cuvette check (Automatic by analyzer)'
      ]
    }
  ],

  // Realistic Initial Equipment Master Seed (รวมตัวอย่างเครื่องในแผนกต่างๆ)
  initialEquipment: [
    {
      id: 'PPCH-EQ-DEF-001',
      assetCode: 'EQ-68-DEF-001',
      name: 'เครื่อง Defibrillator ชนิดสองทิศทาง (Biphasic)',
      formId: 'defibrillator',
      model: 'Zoll R Series Plus',
      serialNo: 'ZR-2024-8891',
      frequency: 'daily',
      homeDept: 'ER',
      currentDept: 'ER',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-DEF-002',
      assetCode: 'EQ-68-DEF-002',
      name: 'เครื่อง Defibrillator พร้อม Pacing',
      formId: 'defibrillator',
      model: 'Mindray BeneHeart D3',
      serialNo: 'MR-D3-99120',
      frequency: 'daily',
      homeDept: 'ICU',
      currentDept: 'ICU',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-VENT-001',
      assetCode: 'EQ-67-VENT-001',
      name: 'เครื่องช่วยหายใจชนิดควบคุมด้วยปริมาตรและความดัน',
      formId: 'ventilator',
      model: 'Hamilton-C3',
      serialNo: 'HM-C3-00452',
      frequency: 'daily',
      homeDept: 'ICU',
      currentDept: 'ICU',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-VENT-002',
      assetCode: 'EQ-67-VENT-002',
      name: 'เครื่องช่วยหายใจ ICU Ventilator ชนิดเคลื่อนย้าย',
      formId: 'ventilator',
      model: 'Maquet Servo-i',
      serialNo: 'MQ-SV-7714',
      frequency: 'daily',
      homeDept: 'CENTRAL',
      currentDept: 'CENTRAL',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-HF-001',
      assetCode: 'EQ-68-HF-001',
      name: 'เครื่อง High Flow Nasal Cannula (Airvo 2)',
      formId: 'high_flow',
      model: 'Fisher & Paykel Airvo 2',
      serialNo: 'FP-AV2-1920',
      frequency: 'daily',
      homeDept: 'ER',
      currentDept: 'ER',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-HF-002',
      assetCode: 'EQ-68-HF-002',
      name: 'เครื่อง High Flow Nasal Cannula (Airvo 2)',
      formId: 'high_flow',
      model: 'Fisher & Paykel Airvo 2',
      serialNo: 'FP-AV2-1921',
      frequency: 'daily',
      homeDept: 'CENTRAL',
      currentDept: 'CENTRAL',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-INF-001',
      assetCode: 'EQ-69-INF-001',
      name: 'เครื่อง Infusion Pump (ควบคุมสารน้ำ)',
      formId: 'infusion_pump',
      model: 'Terumo TE-LM700',
      serialNo: 'TR-LM-6621',
      frequency: 'daily',
      homeDept: 'WARD23',
      currentDept: 'WARD23',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-INF-002',
      assetCode: 'EQ-69-INF-002',
      name: 'เครื่อง Infusion Pump (ควบคุมสารน้ำ)',
      formId: 'infusion_pump',
      model: 'Terumo TE-LM700',
      serialNo: 'TR-LM-6622',
      frequency: 'daily',
      homeDept: 'CENTRAL',
      currentDept: 'CENTRAL',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-VS-001',
      assetCode: 'EQ-68-VS-001',
      name: 'เครื่อง Vital Signs Monitor พร้อม NIBP & SpO2',
      formId: 'vital_signs',
      model: 'Mindray uMEC10',
      serialNo: 'MR-UM10-4411',
      frequency: 'daily',
      homeDept: 'OPD',
      currentDept: 'OPD',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-VS-002',
      assetCode: 'EQ-68-VS-002',
      name: 'เครื่อง Vital Signs Monitor พร้อม NIBP & SpO2',
      formId: 'vital_signs',
      model: 'Mindray uMEC10',
      serialNo: 'MR-UM10-4412',
      frequency: 'daily',
      homeDept: 'ER',
      currentDept: 'ER',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-ANES-001',
      assetCode: 'EQ-66-ANES-001',
      name: 'เครื่องให้ยาสลบพร้อมระบบช่วยหายใจ (OR 1)',
      formId: 'anesthesia',
      model: 'Dräger Fabius Plus',
      serialNo: 'DR-FB-1033',
      frequency: 'daily',
      homeDept: 'OR',
      currentDept: 'OR',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-EKG-001',
      assetCode: 'EQ-67-EKG-001',
      name: 'เครื่อง EKG 12 Leads พร้อมตีพิมพ์ผล',
      formId: 'ekg_monitor',
      model: 'Nihon Kohden Cardiofax M',
      serialNo: 'NK-CF-9011',
      frequency: 'daily',
      homeDept: 'ER',
      currentDept: 'ER',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-US-001',
      assetCode: 'EQ-67-US-001',
      name: 'เครื่องตรวจคลื่นเสียงสะท้อนความถี่สูง Ultrasound',
      formId: 'ultrasound',
      model: 'GE LOGIQ P9',
      serialNo: 'GE-LQ-5541',
      frequency: 'monthly',
      homeDept: 'XRAY',
      currentDept: 'XRAY',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-US-002',
      assetCode: 'EQ-68-US-002',
      name: 'เครื่อง Ultrasound ชนิดเคลื่อนย้ายข้างเตียง (Point-of-Care)',
      formId: 'ultrasound',
      model: 'SonoSite Edge II',
      serialNo: 'SS-ED2-8840',
      frequency: 'monthly',
      homeDept: 'ICU',
      currentDept: 'ICU',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // ===== เครื่องมือแพทย์และอุปกรณ์ แผนกห้องปฏิบัติการ (Laboratory) =====
    // 1. FM-PPCH-LAB-019: UPS Lab
    {
      id: 'PPCH-EQ-LAB-UPS-001',
      assetCode: 'EQ-LAB-UPS-001',
      name: 'เครื่องสำรองไฟห้องปฏิบัติการ UPS (Lab Central UPS)',
      formId: 'lab_ups',
      model: 'APC Smart-UPS 3000VA',
      serialNo: 'AS-3000-LAB01',
      frequency: 'quarterly',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 2. FM-PPCH-LAB-049: Cobas h232 (3 เครื่อง)
    {
      id: 'PPCH-EQ-LAB-COBAS-001',
      assetCode: 'EQ-LAB-COBAS-001',
      name: 'เครื่องวิเคราะห์ Cardiac Marker Cobas h232 (เครื่องที่ 1)',
      formId: 'lab_cobas_h232',
      model: 'Roche Cobas h232',
      serialNo: 'KQ03008166',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-COBAS-002',
      assetCode: 'EQ-LAB-COBAS-002',
      name: 'เครื่องวิเคราะห์ Cardiac Marker Cobas h232 (เครื่องที่ 2)',
      formId: 'lab_cobas_h232',
      model: 'Roche Cobas h232',
      serialNo: 'KQ0304874',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-COBAS-003',
      assetCode: 'EQ-LAB-COBAS-003',
      name: 'เครื่องวิเคราะห์ Cardiac Marker Cobas h232 (เครื่องที่ 3)',
      formId: 'lab_cobas_h232',
      model: 'Roche Cobas h232',
      serialNo: 'KQ0132536',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 3. FM-PPCH-LAB-057: อุณหภูมิห้อง Lab แยก 5 ห้อง
    {
      id: 'PPCH-EQ-LAB-ROOM-001',
      assetCode: 'EQ-LAB-ROOM-001',
      name: 'ระบบควบคุมอุณหภูมิห้องปฏิบัติการ (Laboratory)',
      formId: 'lab_room_temp',
      model: 'Thermo-Hygrometer Point 1',
      serialNo: 'TH-LAB-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-ROOM-002',
      assetCode: 'EQ-LAB-ROOM-002',
      name: 'ระบบควบคุมอุณหภูมิห้อง Immunology',
      formId: 'lab_room_temp',
      model: 'Thermo-Hygrometer Point 2',
      serialNo: 'TH-IMM-02',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-ROOM-003',
      assetCode: 'EQ-LAB-ROOM-003',
      name: 'ระบบควบคุมอุณหภูมิห้อง Blood bank (ธนาคารเลือด)',
      formId: 'lab_room_temp',
      model: 'Thermo-Hygrometer Point 3',
      serialNo: 'TH-BB-03',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-ROOM-004',
      assetCode: 'EQ-LAB-ROOM-004',
      name: 'ระบบควบคุมอุณหภูมิห้อง Bacteria (จุลชีววิทยา)',
      formId: 'lab_room_temp',
      model: 'Thermo-Hygrometer Point 4',
      serialNo: 'TH-BAC-04',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-ROOM-005',
      assetCode: 'EQ-LAB-ROOM-005',
      name: 'ระบบควบคุมอุณหภูมิห้อง Storage (คลังเก็บน้ำยา/เวชภัณฑ์)',
      formId: 'lab_room_temp',
      model: 'Thermo-Hygrometer Point 5',
      serialNo: 'TH-STO-05',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 4. FM-PPCH-LAB-060: ตู้แช่แข็ง แยก 2 ตู้
    {
      id: 'PPCH-EQ-LAB-FRZ-001',
      assetCode: 'EQ-LAB-FRZ-001',
      name: 'ตู้เย็นแช่ FFP (Fresh Frozen Plasma Freezer)',
      formId: 'lab_freezer',
      model: 'Biomedical Deep Freezer -20°C',
      serialNo: 'FZ-FFP-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-FRZ-002',
      assetCode: 'EQ-LAB-FRZ-002',
      name: 'ตู้เย็นเก็บ Control (Quality Control Freezer)',
      formId: 'lab_freezer',
      model: 'Biomedical Deep Freezer -20°C',
      serialNo: 'FZ-CTL-02',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 5. FM-PPCH-LAB-061: Waterbath แยก 2 เครื่อง
    {
      id: 'PPCH-EQ-LAB-WB-001',
      assetCode: 'EQ-LAB-WB-001',
      name: 'อ่างควบคุมอุณหภูมิน้ำ Water bath 1',
      formId: 'lab_waterbath',
      model: 'Precision Water Bath 37°C',
      serialNo: 'WB-LAB-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-WB-002',
      assetCode: 'EQ-LAB-WB-002',
      name: 'อ่างควบคุมอุณหภูมิน้ำ Water bath 2',
      formId: 'lab_waterbath',
      model: 'Precision Water Bath 37°C',
      serialNo: 'WB-LAB-02',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 6. FM-PPCH-LAB-062: ตู้เย็นเก็บน้ำยา แยก 3 ตู้
    {
      id: 'PPCH-EQ-LAB-REF-001',
      assetCode: 'EQ-LAB-REF-001',
      name: 'ตู้แช่น้ำยา 1 (Reagent Refrigerator 1)',
      formId: 'lab_refrigerator',
      model: 'Pharmacy & Laboratory Refrigerator 2-8°C',
      serialNo: 'RF-RGT-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-REF-002',
      assetCode: 'EQ-LAB-REF-002',
      name: 'ตู้แช่น้ำยา 2 (Reagent Refrigerator 2)',
      formId: 'lab_refrigerator',
      model: 'Pharmacy & Laboratory Refrigerator 2-8°C',
      serialNo: 'RF-RGT-02',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    {
      id: 'PPCH-EQ-LAB-REF-003',
      assetCode: 'EQ-LAB-REF-003',
      name: 'ตู้แช่สิ่งส่งตรวจ (Specimen Refrigerator)',
      formId: 'lab_refrigerator',
      model: 'Biomedical Specimen Refrigerator 2-8°C',
      serialNo: 'RF-SPM-03',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 7. FM-PPCH-LAB-091: BSC Class II
    {
      id: 'PPCH-EQ-LAB-BSC-001',
      assetCode: 'EQ-LAB-BSC-001',
      name: 'ตู้ตรวจชีวนิรภัย BSC Class II (MICRO TECH)',
      formId: 'lab_bsc',
      model: 'Micro Tech Class II Type A2',
      serialNo: 'MT-BSC2-2024-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    },
    // 8. FM-PPCH-LAB-099: Chemistry Mindray (BS-600M)
    {
      id: 'PPCH-EQ-LAB-CHM-001',
      assetCode: 'EQ-LAB-CHM-001',
      name: 'เครื่องวิเคราะห์เคมีคลินิกอัตโนมัติ Chemistry Mindray (BS-600M)',
      formId: 'lab_mindray_bs600m',
      model: 'Mindray BS-600M',
      serialNo: 'MR-BS600M-2025-01',
      frequency: 'daily',
      homeDept: 'LAB',
      currentDept: 'LAB',
      status: 'ready',
      lastEvaluatedAt: '',
      lastEvaluatedStatus: 'pending',
      lastEvaluatedBy: '',
      abnormalReason: ''
    }
  ]
};
